/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package finallab.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class ball_t implements lcm.lcm.LCMEncodable
{
    public long nanoTime;
    public double x;
    public double y;
    public double z;
 
    public ball_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5ef23029e3214814L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(finallab.lcmtypes.ball_t.class))
            return 0L;
 
        classes.add(finallab.lcmtypes.ball_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.nanoTime); 
 
        outs.writeDouble(this.x); 
 
        outs.writeDouble(this.y); 
 
        outs.writeDouble(this.z); 
 
    }
 
    public ball_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ball_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static finallab.lcmtypes.ball_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        finallab.lcmtypes.ball_t o = new finallab.lcmtypes.ball_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.nanoTime = ins.readLong();
 
        this.x = ins.readDouble();
 
        this.y = ins.readDouble();
 
        this.z = ins.readDouble();
 
    }
 
    public finallab.lcmtypes.ball_t copy()
    {
        finallab.lcmtypes.ball_t outobj = new finallab.lcmtypes.ball_t();
        outobj.nanoTime = this.nanoTime;
 
        outobj.x = this.x;
 
        outobj.y = this.y;
 
        outobj.z = this.z;
 
        return outobj;
    }
 
}

